### ISSUE TITLE
Make the project multi-platform buildable

### ISSUE THREAD

**Issue by J0XX0** [michalzaq12/electron-nuxt#334]
Hi,

We cannot build this project using wine or CircleCI. It's very impractical to always have to be building on your host-OS based on the current configuration. Can you improve the building process for CI/CD?

Thanks

**Comment by J0XX0** [comment]
Here's an example config (`.circleci/config.yml`): 

```yml
version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn && yarn run build
      - store_artifacts:
          path: /root/project/build

workflows:
  version: 2
  build:
    jobs:
      - build_windows
```
