### ISSUE TITLE
Application entry file does not exist error when running build in Github Action

### ISSUE THREAD

**Issue by nwittwer** [michalzaq12/electron-nuxt#572]
Hi, I'm trying to use the [Github Action](https://github.com/michalzaq12/action-electron-nuxt) with this template (although I've upgrade some of the packages). When I run `yarn run build` or `yarn electron-builder --mac` locally, the builds work great. But once I try using the Github Action, I keep hitting the error below after the Nuxt-Electron has completed.

Error: `Application entry file "dist/main/index.js" in the "/Users/runner/work/reflex/reflex/dist/mac/Reflex.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.`

Logs:
```
[SUCCEED] Electron-nuxt: Build completed
Done in 104.65s.

Building the Electron app…
yarn run v1.22.5
$ /Users/runner/work/reflex/reflex/node_modules/.bin/electron-builder --mac
  • electron-builder  version=22.9.1 os=19.6.0
  • artifacts will be published if draft release exists  reason=CI detected
  • packaging       platform=darwin arch=x64 electron=11.1.0 appOutDir=dist/mac
  ⨯ Application entry file "dist/main/index.js" in the "/Users/runner/work/reflex/reflex/dist/mac/Reflex.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.  

Error: Application entry file "dist/main/index.js" in the "/Users/runner/work/reflex/reflex/dist/mac/Reflex.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.

... stack trace ...

child_process.js:660
    throw err;
    ^

Error: Command failed: yarn run electron-builder --mac 
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/Users/runner/work/_actions/michalzaq12/action-electron-nuxt/v1/index.js:21:27)
    at runAction (/Users/runner/work/_actions/michalzaq12/action-electron-nuxt/v1/index.js:128:2)
    at Object.<anonymous> (/Users/runner/work/_actions/michalzaq12/action-electron-nuxt/v1/index.js:136:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
```

---

package.json
```json
"build": "node .electron-nuxt/build.js"
```

builder.config.js
```js
module.exports = {
  asar: false,
  ...,
  directories: {
    output: 'build',
  },
  files: [
    'package.json',
    {
      from: 'dist/main/',
      to: 'dist/main/',
    },
    {
      from: 'dist/renderer',
      to: 'dist/renderer/',
    },
  ],
  ...
}
```

.github/workflows/build.yml
```yml
## Based on https://github.com/samuelmeuli/mini-diary/blob/master/.github/workflows/release.yml
name: Build/release

on:
  push:
    branches:
      - master
      - dev

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build/release Electron app
        uses: michalzaq12/action-electron-nuxt@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          # type: string
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0")
          # then create a Github release
          # type: boolean
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # Mac certificate info
          mac_certs: ${{ secrets.CSC_LINK }}
          mac_certs_password: ${{ secrets.CSC_KEY_PASSWORD }}
```
